In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3],[3,2,3]])
print(b)

[[1 2 3]
 [3 2 3]]


In [8]:
# Get Dimensions
a.ndim
b.ndim

2

In [10]:
# Get Shape
a.shape
b.shape

(2, 3)

In [4]:
# Get Type
a.dtype

dtype('int32')

In [5]:
# Get Size
a.itemsize

4

In [6]:
# Get total Size
a.nbytes


12

Accessing/ Changing specific elements, rows, columns, etc

In [32]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element [r,c]
a[1,5] # or [1,-2]

13

In [21]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific columns
a[:, 2]

array([ 3, 10])

In [23]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [36]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-D Example

In [8]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Get specific element (work outside in)
b[0,1,:] = [9,9]

Initializing Different types of arrays

In [12]:
# All 0s matrix
np.zeros(5)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# All is matrix
np.ones((4,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [58]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [59]:
  # Any other number (full_like)
np.full_like(a,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [60]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.98253784, 0.31989062],
       [0.60533221, 0.27524637],
       [0.82597701, 0.47744762],
       [0.14802972, 0.26790309]])

In [62]:
# Random integers values
np.random.randint( 2,4,size=(3,3))

array([[2, 2, 2],
       [2, 3, 3],
       [2, 2, 3]])

In [63]:
# Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
# Didn't Understand
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [69]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 5
print(z)

# Didn't Understand
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 5. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


*****Be carefull when copying arrays !!!

In [72]:
# here we didn't specify that we are copying
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [73]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


Mathematics

In [74]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [77]:
a + 2

array([3, 4, 5, 6])

In [76]:
a - 2

array([-1,  0,  1,  2])

In [78]:
a * 2

array([2, 4, 6, 8])

In [81]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [83]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [84]:
a ** 2

array([ 1,  4,  9, 16])

In [85]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [101]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [95]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [13]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.min(stats)

1

In [16]:
np.max(stats, axis=1)

array([3, 6])

Reorganizing Arrays


In [107]:
before = np.array([[1,2,3,4],[5,5,6,7]])
before

after = before.reshape(8,1)
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [5],
       [6],
       [7]])

In [108]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,3))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.]])